server:
  port: 8093

spring:
  cloud:
    stream:
      # 生产者配置
      bindings:
        chain-out-0: # 对应代码里的 "chain-out-0"
          content-type: application/json
          destination: chain-result-topic      # 发送到 RocketMQ 的 Topic 名称
          group: chain-group                   # 发送者所在的 Group
          binder: rocketmq                     # 指定使用 RocketMQ
  application:
    name: business-blockchain
  profiles:
    active: prod
  config:
    import:
      - classpath:/datasource.yml
      - classpath:/rpc.yml
      - classpath:/config.yml
      - classpath:/cache.yml
      - classpath:/stream.yml