server:
  # 网关服务端口
  port: 8080

spring:
  application:
    # 当前应用名称（注册到 Nacos 的服务名）
    name: gateway
  config:
    # 引入公共配置（Redis、Nacos 等）
    import:
      - classpath:cache.yml
      - classpath:config.yml
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              # 开启基于服务发现的路由（可以通过服务名 lb://xxx 转发）
              enabled: true
              lower-case-service-id: true
          routes:
            # 认证中心路由
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**, /token/**
            # 用户服务路由
            - id: business-user
              uri: lb://business-user
              predicates:
                - Path=/user/**
            # 藏品服务路由
            - id: business-artwork
              uri: lb://business-artwork
              predicates:
                - Path=/artwork/**
            # 区块链服务路由
            - id: business-blockchain
              uri: lb://business-blockchain
              predicates:
                - Path=/blockchain/**
            # 交易服务路由
            - id: business-trade
              uri: lb://business-trade
              predicates:
                - Path=/trade/**
            # 管理员模块路由
            - id: admin
              uri: lb://admin
              predicates:
                - Path=/admin/**
