server:
  port: 8096
spring:
  config:
    import:
      - classpath:/rpc.yml
      - classpath:/config.yml
      - classpath:/file.yml
      - classpath:/base.yml
  application:
    name: business-product
