server:
  port: 8092

spring:
  application:
    name: business-artwork
  config:
    import:
      - classpath:/datasource.yml
      - classpath:/rpc.yml
      - classpath:/base.yml
      - classpath:/config.yml
      - classpath:/cache.yml
      - classpath:/file.yml
      - classpath:/es.yml